### ISSUE TITLE
Invalid rootMargin type expected

### ISSUE THREAD

**Issue by marcosdabraunfels** [AvraamMavridis/react-intersection-visible#20]
I am using the `rootMargin` option as such:

```javascript
 <IntersectionVisible onHide={() => this.onHide()} onShow={() => this.onShow()} options={{ rootMargin: '-100px 0px 0px 0px' }}>
```
But I am receiving an error in the browser console:

```
Warning: Failed prop type: Invalid prop `options.rootMargin` of type `string` supplied to `IntersectionVisible`, expected `number`.
```

Unless I'm misreading, it seems that `string` is the expected type by the [IntersectionObserver API](https://w3c.github.io/IntersectionObserver/#dom-intersectionobserverinit-rootmargin). For kicks, I used a `number` and received the following error:

```
Uncaught DOMException: Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.
```

**Comment by modkaffes** [comment]
@marcosdabraunfels, another thing I noticed (after switching `rootMargin`’s propType to `string`) was that the API doesn’t accept a `0` margin value without the `px` suffix, like CSS does.

So for example, `options={{ rootMargin: '-100px 0 -100px 0' }}` throws the `rootMargin must be specified in pixels or percent` error, whereas `options={{ rootMargin: '-100px 0px -100px 0px' }}` works properly.
