### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by tomfordweb** [AvraamMavridis/react-intersection-visible#23]
You have a slight error in your docs. There is an extra greater than sign after the onHide prop.
```
<IntersectionVisible onIntersect={ e => this.onIntersect( e ) }
                                    onHide={ e => this.onHide( e ) }>
                                     onShow={ e => this.onShow( e ) }> 
```

Thanks for sharing this package, I have found it very useful for my current project!

**Comment by AvraamMavridis** [comment]
@tomfordweb do you may wanna open a PR? otherwise I am gonna fix it soon, thx for pointing it out

**Comment by tomfordweb** [comment]
Done.

**Comment by AvraamMavridis** [comment]
@tomfordweb thx
