### ISSUE TITLE
Broken SSR

### ISSUE THREAD

**Issue by nickensoul** [AvraamMavridis/react-intersection-visible#26]
Thanks for this component at first!
`import 'intersection-observer';`
breaks down SSR due it uses window object without checking for available inside of it.
Please, can you remove this import and warn this in Readme instead?
Checked at Gatsby 2 at build command.
Thanks!

**Comment by AvraamMavridis** [comment]
We need the polyfill though, we need to find a way to achieve both.

**Comment by Gregoor** [comment]
What's the polyfill needed for? Afaik create-react-app transpiles node_modules since V2.

**Comment by AvraamMavridis** [comment]
@Gregoor sorry I dont get it, why `create-react-app` is related? The polyfill is needed for browsers that do not implement the IntersectionObserver API.

**Comment by AvraamMavridis** [comment]
@Gregoor @nickensoul in any case I will remove the import
